### ISSUE TITLE
Syntax error at run time　実行時に構文エラーが起きる

### ISSUE THREAD

**Issue by akumaginkou** [lindwurm/madoka#5]
実行条件
ubuntumate20.04lts
.envはサンプルのまま
コマンド実行時下記のようなエラーが発生する
問題がないのならいいが知らせておく
./build.sh
.env: 行 28: 対応する `"' を探索中に予期しないファイル終了 (EOF) です
.env: 行 29: 構文エラー: 予期しないファイル終了 (EOF) です
指定された引数は0個です。
仕様:  [ビルドディレクトリ] [ターゲット] [オプション]

**Comment by lindwurm** [comment]
.env.sample にミスが有りました。ありがとうございます 7db5cca59f6cbcd8b6eede2e75547e60c3f24da6
