### ISSUE TITLE
ビルド後エラーが何個か出て、出力先もおかしい

### ISSUE THREAD

**Issue by akumaginkou** [lindwurm/madoka#7]
デフォルト設定のままでビルドを走らせると出来上がったromの出力先がおかしくなる
madokaの一つ上の階層に /~/romが生成される
md5sumについてはsha256sumに修正すれば通ると思う

~/
|
|-- build/
|   |-- floko/
|   |-- lineage/
|   |--~/
       |--rom/
          |-- ${device}/       ←ここに出力される
|   |-- log/
|   |   |-- fail/
|   |   `-- success/
|   `-- madoka/
|       |-- build.sh
|       |-- LICENSE
|       `-- README.md
`

下記からログ

#### build completed successfully (05:29 (mm:ss)) ####

renamed 'log/20211105_035633_lineage_X01BD.log' -> 'log/success/20211105_035633_lineage_X01BD.log'

renamed 'lineage/out/target/product/X01BD/lineage-18.1-20211105-UNOFFICIAL-X01BD.zip' -> 'lineage-18.1-20211105_035633-UNOFFICIAL-X01BD.zip'
renamed 'lineage-18.1-20211105_035633-UNOFFICIAL-X01BD.zip' -> '~/rom/X01BD/lineage-18.1-20211105_035633-UNOFFICIAL-X01BD.zip'
mv: 'lineage/out/target/product/X01BD/lineage-18.1-20211105-UNOFFICIAL-X01BD.zip.md5sum' を stat できません: そのようなファイルやディレクトリはありません
mv: 'lineage/out/target/product/X01BD/changelog_X01BD.txt' を stat できません: そのようなファイルやディレクトリはありません

**Comment by akumaginkou** [comment]
自分で修正できたのでクローズします

**Comment by lindwurm** [comment]
問題洗い出せたので直します

## 要修正

### 出力先

https://github.com/lindwurm/madoka/blob/7db5cca59f6cbcd8b6eede2e75547e60c3f24da6/.env.sample#L28

- `$HOME` 使ったほうが良い気がする
  -  未確認


### md5 -> sha256

https://github.com/lindwurm/madoka/blob/7db5cca59f6cbcd8b6eede2e75547e60c3f24da6/build.sh#L180

- LineageOSはmd5からsha256に移行済
  - https://github.com/LineageOS/android_vendor_lineage/commit/cb30d255fbbb76bed0caeade36257a3d461ef4f3
- FlokoROMも次のセキュリティパッチリリースで対応予定

### changelog がない

https://github.com/lindwurm/madoka/blob/7db5cca59f6cbcd8b6eede2e75547e60c3f24da6/build.sh#L181

- LineageOSはchangelogを吐かない
- crDroid/FlokoROMが吐く https://github.com/FlokoROM/vendor_floko/blob/11.0/build/tools/changelog.sh

**Comment by akumaginkou** [comment]
早い対応ありがとうございます。
